```{r}
current_path = rstudioapi::getActiveDocumentContext()$path
setwd(dirname(current_path))
source("anovatab.R")
```
- Read data 
```{r}
turkey=read.table("turkey.txt",header=T)
turkey
```
  
###first fit - common slopes model

```{r}
fit_turkey=lm(weight~factor(feed)+age,data=turkey)
summary(fit_turkey)

```
```{r}
anovatab(fit_turkey)

```
  
## partial F tests
### test for age
```{r}
library(multcomp)

```

```{r}
L=matrix(c(0,0,0,1),nrow=1)
```

```{r}
glh=glht(fit_turkey,linfct=L)
summary(glh,test=Ftest())
```
  
### compare feed types b and c

```{r}
L1=matrix(c(0,1,-1,0),nrow=1)
L1
```

```{r}
glh1=glht(fit_turkey,linfct=L1)
summary(glh1,test=Ftest())
```
  
### do we need feed type as a factor?
```{r}
L2=matrix(c(0,1,0,0,0,0,1,0),byrow=T,nrow=2)
L2
```

```{r}
glh2=glht(fit_turkey,linfct=L2)
summary(glh2,test=Ftest())
```
  
### more convenient way of doing this…
```{r}
drop1(fit_turkey,test='F')

```
geometry of this model…
```{r}
turkey$colour='blue'
turkey$colour[turkey$feed=='b']='red'
turkey$colour[turkey$feed=='c']='darkgreen'
with(turkey,plot(age,weight,pch=20,cex=2,col=colour))
abline(-0.4975,0.4868,col='blue',lwd=2)
abline(-0.4971-0.2735,0.4868,col='red',lwd=2)
abline(-0.4971+1.9184,0.4868,col='darkgreen',lwd=2)
legend('bottomright',legend=c('Type a','Type b','Type c' ),lwd=2,col=c('blue','red','darkgreen'))
```
  
### Iteration model:
```{r}
fit_turkey2=update(fit_turkey,.~.+age:factor(feed))
fit_turkey2
```


### plot of the interaction model…
```{r}
with(turkey,plot(age,weight,pch=20,cex=2,col=colour))
abline(-0.97912,0.50604,col='blue',lwd=2)
abline(-0.97912+.67912,0.50604-0.03604,col='red',lwd=2)
abline(-0.97912+3.45412,0.50604-0.06104,col='darkgreen',lwd=2)
legend('bottomright',legend=c('Type a','Type b','Type c' ),lwd=2,col=c('blue','red','darkgreen'))
```
  

### NB: same as
```{r}
fit_turkey2a=lm(weight~factor(feed)+age+age:factor(feed),data=turkey)
## as same as 
fit_turkey2b=lm(weight~factor(feed)*age,data=turkey)
```


### assess this: do we need the interaction - use a GLH on beta 4 and beta 5
```{r}
drop1(fit_turkey2,test='F')
```

