```{r}
current_path = rstudioapi::getActiveDocumentContext()$path
setwd(dirname(current_path))
```

## Normality assumption
```{r}
# qq plot
# i=1
qnorm((1-0.375)/(20+.025))
```
```{r}
# i=2
qnorm((2-0.375)/(20+.025))
```

```{r}
# i=3
qnorm((3-0.375)/(20+.025))
```

```{r}
# i=20
qnorm((20-0.375)/(20+.025))
```

## Forestry Data

```{r}
forestry=read.table('forestry.txt',header=T)
attach(forestry)
tree_years=n*age
comp=hd/n
forestry=cbind(forestry,tree_years,comp)
fit=lm(mdbh~hd+tree_years+comp,data=forestry)
rstudent=rstudent(fit)
qqnorm(rstudent,pch=20,col='blue',cex=2)
```

```{r}
bf_small=read.csv('bodyfat_small.csv',header=T)
fit1=lm(body_fat~Age+Height+Neck,data=bf_small);cbind(round(fit1$coeff,3))
```

```{r}
fit2=lm(body_fat~Age+Height+Neck+Chest,data=bf_small);cbind(round(fit2$coeff,3))

```

```{r}
fit3=lm(body_fat~Age+Height+Neck+Chest+Weight,data=bf_small);cbind(round(fit3$coeff,3))

```
```{r}
summary(fit1);summary(fit2);summary(fit3)

```
```{r}
fit4=lm(body_fat~Age+Height+Weight,data=bf_small);summary(fit4)

```

```{r}
preds=bf_small[,3:7]
round(cor(preds),2)

```

```{r}
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y))
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste0(prefix, txt)
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = cex.cor * r)
}
pairs(preds,upper.panel=panel.cor)
```

```{r}
install.packages('car')
library(car)
vif(fit3)

```

